#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# 用户程序中定义的那些系统调用函数，比如fork,open等等，链接之后，都指向这里定义的这些

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}


# .global fork
# fork:
#     li a7, SYS_fork       # 把系统调用编号加载到 a7 寄存器
#     ecall                 # 触发陷阱，陷入内核
#     ret                   # 返回


entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");